# Generated by Django 4.2.5 on 2023-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phonenumber", models.IntegerField()),
                ("messages", models.CharField(max_length=500)),
            ],
        ),
    ]
