# Generated by Django 4.2.5 on 2023-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websnap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
    ]
